targets:
  $default:
    sources:
      include:
        - app_config.yaml
        - app_config_overrides.yaml
    builders:
      app_config_generator:app_config:
        options:
          use_record_type: true
          output_file: lib/src/config/app_config.g.dart
