builders:
  app_config:
    import: "package:app_config_generator/app_config_generator.dart"
    builder_factories: ["appConfig"]
    build_extensions: {".yaml": [".g.dart"]}
    auto_apply: dependents
    build_to: source 