name: app_config_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/AoEiuV020/app_config_generator

environment:
  sdk: ^3.6.0

dependencies:
  build: ^2.4.0
  yaml: ^3.1.2
  code_builder: ^4.5.0
  dart_style: ^2.3.1

dev_dependencies:
  lints: ^5.0.0
  melos: ^6.2.0
  test: ^1.24.0
